version: "3.7"

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    volumes:
      - rentals-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_DATABASE: rentals
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

volumes:
  rentals-mysql-data: